version: '3.8'
services:
  api-gateway:
    image: api-gateway:0.0.1
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - local-network

networks:
  local-network:
    external: true